@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.accessToken}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Clara Sendin",
    "email": "clarasendin@email.com",
    "password": "010203"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email": "clarasendin@email.com",
    "password": "010203"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Title",
    "content": "Content"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}
